<a href="https://colab.research.google.com/github/NgocSon-AI/Sun-Study-Generative-AI/blob/main/Data%20Preprocessing%20and%20Embedding/BagOfWord.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Some common terms to remember:


1.   Corpus
2.   Vocabulary
3.   Document
4.   Word



## Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch sunsun",
                         "sunsun watch sunsun",
                         "people write comment",
                          "sunsun write comment"], "output":[1,1,0,0]})
df

text  output
0   people watch sunsun       1
1   sunsun watch sunsun       1
2  people write comment       0
3  sunsun write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
bow

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [6]:
# Gán số thứ tự theo bảng chữ cái
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'sunsun': 2, 'write': 4, 'comment': 0}


In [7]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 0, 2, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1]])

In [8]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 0 2 1 0]]
[[1 1 0 0 1]]


In [9]:
cv.transform(["people write comment sunsun"]).toarray()

array([[1, 1, 1, 0, 1]])

In [10]:
X = bow.toarray()
y = df['output']

In [11]:
X


array([[0, 1, 1, 1, 0],
       [0, 0, 2, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1]])

## N-grams

In [12]:
df = pd.DataFrame({"text":["people watch sunsun",
                         "sunsun watch sunsun",
                         "people write comment",
                          "sunsun write comment"], "output":[1,1,0,0]})
df

text  output
0   people watch sunsun       1
1   sunsun watch sunsun       1
2  people write comment       0
3  sunsun write comment       0

In [13]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [14]:
bow = cv.fit_transform(df['text'])

In [15]:

print(cv.vocabulary_)

{'people watch': 0, 'watch sunsun': 4, 'sunsun watch': 2, 'people write': 1, 'write comment': 5, 'sunsun write': 3}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 0 1 0]]
[[0 0 1 0 1 0]]
[[0 1 0 0 0 1]]


In [17]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [18]:
bow = cv.fit_transform(df['text'])

In [19]:
print(cv.vocabulary_)

{'people watch sunsun': 0, 'sunsun watch sunsun': 2, 'people write comment': 1, 'sunsun write comment': 3}


In [20]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 0]]
[[0 0 1 0]]
[[0 1 0 0]]


## TF - IDF (Term frequency - Inverse document frequency)

## CORPUS

In [21]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [23]:
arr = tfid.fit_transform(df['text']).toarray()

TF(t,d) = Số lần từ t xuất hiện trong tài liệu d / Tổng số từ trong tài liệu d

IDF(t, D) = log(Tổng số tài liệu / Số tài liệu có từ t)

TF-IDF(t,d,D) = Tf(t,d) x IDF(t, D)
- Tìm kiếm thông tin
- Phân loại văn bản
- Phân nhóm tài liệu
- Tạo các hệ thông gợi ý và lọc thông

In [24]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
